const animalInfo = [
    {
        "id": 1,
        "Name": "African Forest Elephant",
        "animalIntroduction": "<p>African forest elephants are the elusive cousin of the African savanna elephant. They inhabit the dense rainforests of west and central Africa. Their preference for dense forest habitat prohibits traditional counting methods such as visual identification. Their population is usually estimated through \\\"dung counts\\\"—an analysis on the ground of the density and distribution of the feces.</p><p>African forest elephants are smaller than African savanna elephants, the other African elephant species. Their ears are more oval-shaped and their tusks are straighter and point downward (the tusks of savanna elephants curve outwards). There are also differences in the size and shape of the skull and skeleton. Forest elephants also have a much slower reproductive rate than savanna elephants, so they cannot bounce back from population declines as quickly at the same rate. Their last strongholds are located in Gabon and the Republic of Congo, with smaller populations remaining in other African countries (Cameroon, Central African Republic, Equatorial Guinea) and Côte d'Ivoire, Liberia, and Ghana in west Africa.</p><p>African forest elephants live in family groups of up to 20 individuals and forage on leaves, grasses, seeds, fruit, and tree bark. Since the diet of forest elephants is dominated by fruit, they play a crucial role in dispersing many tree species, particularly the seeds of large trees which tend to have high carbon content. They are therefore referred to as the 'mega-gardener of the forest'. To supplement their diet with minerals, they gather at mineral-rich waterholes and mineral licks found throughout the forest.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/African Forest Elephant.jpg",
        "sideImage": "images/Animals_prev+next/African Forest Elephant",
        "nextSideImage": "images/Animals_prev+next/African Savanna Elephant.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Yangtze Finless Porpoise.jpg",
        "status": "Critically Endangered",
        "height": "8-10 feet",
        "weight": "2-5 tons",
        "habitats": "dense tropical forests",
        "scientiicName": "",
        "nextAnimalName": "African Savanna Elephant",
        "previousAnimalName": "Yangtze Finless Porpoise",
        "nextAnimalStatus": "Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 2,
        "Name": "African Savanna Elephant",
        "animalIntroduction": "<p>African savanna elephants are the largest species of elephant and the biggest terrestrial animal on Earth. They are easily distinguished by their very large ears—which allow them to radiate excess heat—and front legs which are noticeably longer than the hind legs. </p><p>African savanna elephants are found in 23 countries and live in a variety of habitats, from open and wooded savannas to even some deserts and forests. The largest populations are in Southern and Eastern African countries, including Botswana, Zimbabwe, Tanzania, Kenya, Namibia, Zambia, and South Africa.</p><p>As a result of their visibility within the open areas where they live, African savanna elephants are well studied and populations are easily estimated. Each family unit usually consists of around 10 females and their calves, and the bulls associate with these herds only during mating. Several family units often join together to form a “clan” consisting of up to several hundred members led by a female matriarch. Due to their habitat, savanna elephants are often found grazing on grasses, but they also browse on a wide variety of plants and fruits. This selection varies depending on the time of year; during the rainy season the elephant will feed more on grass than during the dry season.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/African Savanna Elephant.jpeg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/African Wild Dog.jpg",
        "PreviousSideImage": "images/Animals_prev+next/African Forest Elephant.jpeg",
        "status": "Endangered",
        "height": "10-13 feet",
        "weight": "4-7 tons",
        "habitats": "All of sub-Saharan Africa except for Central Africa’s dense tropical forest",
        "scientiicName": "Loxodonta africana africana",
        "nextAnimalName": "African Wild Dog",
        "previousAnimalName": "African Forest Elephant",
        "nextAnimalStatus": "Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 3,
        "Name": "African Wild Dog",
        "animalIntroduction": "<p>The wild dog is one of the world’s most endangered mammals. The largest populations remain in southern Africa and the southern part of East Africa (especially Tanzania and northern Mozambique).</p><p>Wild dogs are social and gather in packs of around ten individuals, but some packs number more than 40. They are opportunistic predators that hunt medium-sized ruminants, such as gazelles. In a sprint, African wild dogs can reach speeds of more than 44 miles per hour.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/African Wild Dog.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Amur Leopard.jpg",
        "PreviousSideImage": "images/Animals_prev+next/African Savanna Elephant.jpg",
        "status": "Endangered",
        "height": "30 inches",
        "weight": "40-70 pounds",
        "habitats": "Deserts, Forests, Grasslands",
        "scientiicName": "Lycaon pictus",
        "nextAnimalName": "Amur Leopard",
        "previousAnimalName": "African Savanna Elephant",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Endangered"
    },
    {
        "id": 4,
        "Name": "Amur Leopard",
        "animalIntroduction": "<p>People usually think of leopards in the savannas of Africa but in the Russian Far East, a rare subspecies has adapted to life in the temperate forests that make up the northern-most part of the species’ range. Similar to other leopards, the Amur leopard can run at speeds of up to 37 miles per hour. This incredible animal has been reported to leap more than 19 feet horizontally and up to 10 feet vertically.</p><p>The Amur leopard is solitary. Nimble-footed and strong, it carries and hides unfinished kills so that they are not taken by other predators. It has been reported that some males stay with females after mating, and may even help with rearing the young. Several males sometimes follow and fight over a female. They live for 10-15 years, and in captivity up to 20 years. The Amur leopard is also known as the Far East leopard, the Manchurian leopard or the Korean leopard.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Amur Leopard.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Asian Elephant.jpg",
        "PreviousSideImage": "images/Animals_prev+next/African Wild Dog.jpg",
        "status": "Critically Endangered",
        "height": "",
        "weight": "70-105 pounds",
        "habitats": "Temperate, Broadleaf, and Mixed Forests",
        "scientiicName": "Panthera pardus orientalis",
        "nextAnimalName": "Asian Elephant",
        "previousAnimalName": "African Wild Dog",
        "nextAnimalStatus": "Endangered",
        "previousAnimalAtatus": "Endangered"
    },
    {
        "id": 5,
        "Name": "Asian Elephant",
        "animalIntroduction": "<p>The Asian elephant is the largest land mammal on the Asian continent. They inhabit dry to wet forest and grassland habitats in 13 range countries spanning South and Southeast Asia. While they have preferred forage plants, Asian elephants have adapted to surviving on resources that vary based on the area.</p><p>Asian elephants are extremely sociable, forming groups of six to seven related females that are led by the oldest female, the matriarch. Like African elephants, these groups occasionally join others to form larger herds, although these associations are relatively short-lived. In Asia, elephant herd sizes are significantly smaller than those of savannah elephants in Africa.</p><p>More than two-thirds of an elephant's day may be spent feeding on grasses, but it also eats large amounts of tree bark, roots, leaves, and small stems. Cultivated crops such as bananas, rice, and sugarcane are favorite foods. Elephants are always close to a source of fresh water because they need to drink at least once a day.</p><p>In Asia, humans have had close associations with elephants over many centuries, and elephants have become important cultural icons. According to Hindu mythology, the gods (deva) and the demons (asura) churned the oceans in a search for the elixir of life so that they would become immortal. As they did so, nine jewels surfaced, one of which was the elephant. In Hinduism, the powerful deity honored before all sacred rituals is the elephant-headed Lord Ganesha, who is also called the Remover of Obstacles.</p>",
        "timeToRead": 3,
        "image": "images/Animals_main/Asian Elephant.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Black Rhino.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Amur Leopard.jpg",
        "status": "Endangered",
        "height": "6.5–11.5 feet",
        "weight": "Around 11,000 pounds",
        "habitats": "Forests",
        "scientiicName": "Elephas maximus indicus",
        "nextAnimalName": "Black Rhino",
        "previousAnimalName": "Amur Leopard",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 6,
        "Name": "Black Rhino",
        "animalIntroduction": "<p>Black rhinos are the smaller of the two African rhino species. The most notable difference between white and black rhinos are their hooked upper lip. This distinguishes them from the white rhino, which has a square lip. Black rhinos are browsers rather than grazers, and their pointed lip helps them feed on leaves from bushes and trees. They have two horns, and occasionally a third, small posterior horn.</p><p>Populations of black rhino declined dramatically in the 20th century at the hands of European hunters and settlers. Between 1960 and 1995, black rhino numbers dropped by a sobering 98%, to less than 2,500. Since then, the species has made a tremendous comeback from the brink of extinction. Thanks to persistent conservation efforts across Africa, black rhino numbers have doubled from their historic low 20 years ago to around 5,600 today. However, the black rhino is still considered critically endangered, and a lot of work remains to bring the numbers up to even a fraction of what it once was—and to ensure that it stays there. Wildlife crime—in this case, poaching and black-market trafficking of rhino horn—continues to plague the species and threaten its recovery.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Black Rhino.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Bornean Orangutan.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Asian Elephant.jpg",
        "status": "Critically Endangered",
        "height": "5.2 feet",
        "weight": "1,760 -3,080 pounds",
        "habitats": "Semi-Desert Savannah, Woodlands, Forests, Wetlands",
        "scientiicName": "Diceros bicornis",
        "nextAnimalName": "Bornean Orangutan",
        "previousAnimalName": "Asian Elephant",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Endangered"
    },
    {
        "id": 7,
        "Name": "Bornean Orangutan",
        "animalIntroduction": "<p>Bornean orangutan populations have declined by more than 50% over the past 60 years, and the species' habitat has been reduced by at least 55% over the past 20 years.</p><p>The Bornean orangutan differs in appearance from the Sumatran orangutan, with a broader face and shorter beard and also slightly darker in color. Three subspecies are recognized, each localized to different parts of the island:</p><ul><ol>Northwest Bornean orangutans are the most threatened subspecies. Its habitat has been seriously affected by logging and hunting, and a mere 1,500 individuals or so remain. Many habitat patches in the area are small and fragmented.</ol><ol>Northeast Bornean orangutans are the smallest in size and found in Sabah and eastern Kalimantan as far as the Mahakam River.</ol><ol>Central Bornean orangutans are the subspecies with the most animals, with at least 35,000 individuals.</ol></ul>",
        "timeToRead": 4,
        "image": "images/Animals_main/Bornean Orangutan.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Cross River Gorilla.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Black Rhino.jpg",
        "status": "Critically Endangered",
        "height": "3.3 – 4.6 feet",
        "weight": "66–220 pounds",
        "habitats": "Lowland rainforests and tropical, swamp and mountain forests",
        "scientiicName": "Pongo pygmaeus",
        "nextAnimalName": "Cross River Gorilla",
        "previousAnimalName": "Black Rhino",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 8,
        "Name": "Cross River Gorilla",
        "animalIntroduction": "<p>This subspecies of the western gorilla is very similar in appearance to the more numerous western lowland gorilla, but subtle differences can be found in the skull and tooth dimensions. Cross River gorillas live in a region populated by many humans who have encroached upon the gorilla’s territory—clearing forests for timber and to create fields for agriculture and livestock. Poaching occurs in the forests as well, and the loss of even a few of these gorillas has a detrimental effect on such a small population.</p><p>Efforts to protect these animals are focused on securing the forests that house them. WWF and partners have worked with the governments of Cameroon and Nigeria to create a protected area for the Cross River gorilla that spans the border of these two nations.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Cross River Gorilla.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Eastern Lowland Gorilla.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Bornean Orangutan.jpg",
        "status": "Critically Endangered",
        "height": "4 to 5 ½ feet when standing on two feet",
        "weight": "up to 440 pounds",
        "habitats": "",
        "scientiicName": "Gorilla gorilla diehli",
        "nextAnimalName": "Eastern Lowland Gorilla",
        "previousAnimalName": "Bornean Orangutan",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 9,
        "Name": "Eastern Lowland Gorilla",
        "animalIntroduction": "<p>The eastern lowland gorilla—also known as Grauer’s gorilla—is the largest of the four gorilla subspecies. It is distinguished from other gorillas by its stocky body, large hands and short muzzle. Despite its size, eastern lowland gorillas subsist mainly on fruit and other herbaceous materials, just like other gorilla subspecies.</p><p>Years of civil unrest in the Democratic Republic of Congo (DRC) have taken their toll on both the eastern lowland gorilla and the mountain gorilla. The eastern lowland gorilla makes its home in lowland tropical rainforests in the eastern DRC. In the last 50 years, its range has decreased from 8,100 square miles—about the size of the state of Massachusetts— to about 4,600 square miles today. This subspecies may now occupy only 13% of its historical range. There were nearly 17,000 eastern lowland gorillas in the mid-1990s but scientists estimate that the population has declined by more than 50% since then. An accurate accounting of the animals has been impossible for many years because of violence in the region.</p><p>Throughout the unrest, the gorillas have been vulnerable to poaching, even in Kahuzi-Biega National Park, home to the largest population of protected eastern lowland gorillas. Rebels and poachers invaded the park and people set up illegal mines. But, with help from WWF and other organizations, park staff are reestablishing control over the land.</p>",
        "timeToRead": 3,
        "image": "images/Animals_main/Eastern Lowland Gorilla.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Hawksbill Turtle.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Cross River Gorilla.jpg",
        "status": "Critically Endangered",
        "height": "4 to 5 ½ feet when standing on two feet",
        "weight": "up to 440 pounds",
        "habitats": "",
        "scientiicName": "Gorilla beringei graueri",
        "nextAnimalName": "Hawksbill Turtle",
        "previousAnimalName": "Cross River Gorilla",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 10,
        "Name": "Hawksbill Turtle",
        "animalIntroduction": "<p>Hawksbills are named for their narrow, pointed beak. They also have a distinctive pattern of overlapping scales on their shells that form a serrated-look on the edges. These colored and patterned shells make them highly-valuable and commonly sold as \"tortoiseshell\" in markets.</p><p>Hawksbills are found mainly throughout the world's tropical oceans, predominantly in coral reefs. They feed mainly on sponges by using their narrow pointed beaks to extract them from crevices on the reef, but also eat sea anemones and jellyfish. Sea turtles are the living representatives of a group of reptiles that has existed on Earth and travelled our seas for the last 100 million years. They are a fundamental link in marine ecosystems and help maintain the health of coral reefs and sea grass beds.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Hawksbill Turtle.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Javan Rhino.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Eastern Lowland Gorilla.jpg",
        "status": "Critically Endangered",
        "height": "30-35 inches",
        "weight": "90-150 pounds",
        "habitats": "Oceans",
        "scientiicName": "Eretmochelys imbricata",
        "nextAnimalName": "Javan Rhino",
        "previousAnimalName": "Eastern Lowland Gorilla",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 11,
        "Name": "Javan Rhino",
        "animalIntroduction": "<p>Javan rhinos are the most threatened of the five rhino species, with only around 60 individuals that live only in Ujung Kulon National Park in Java, Indonesia. Javan rhinos once lived throughout northeast India and Southeast Asia. Vietnam’s last Javan rhino was poached in 2010.</p><p>This species is a dusky grey color and has a single horn of up to about 10 inches. Its skin has a number of loose folds, giving the appearance of armor plating. The Javan rhino is very similar in appearance to the closely-related greater one-horned rhinoceros, but has a much smaller head and less apparent skin folds.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Javan Rhino.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Orangutan.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Hawksbill Turtle.jpg",
        "status": "Critically Endangered",
        "height": "4.6–5.8 feet",
        "weight": "1,984 - 5,071 pounds",
        "habitats": "Tropical forests",
        "scientiicName": "Rhinoceros sondaicus",
        "nextAnimalName": "Orangutan",
        "previousAnimalName": "Hawksbill Turtle",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 12,
        "Name": "Orangutan",
        "animalIntroduction": "<p>The name orangutan means \"man of the forest\" in the Malay language. In the lowland forests in which they reside, orangutans live solitary existences. They feast on wild fruits like lychees, mangosteens, and figs, and slurp water from holes in trees. They make nests in trees of vegetation to sleep at night and rest during the day. Adult male orangutans can weigh up to 200 pounds. Flanged males have prominent cheek pads called flanges and a throat sac used to make loud verbalizations called long calls. An unflanged male looks like an adult female. In a biological phenomenon unique among primates, an unflanged male can change to a flanged male for reasons that are not yet fully understood.</p><p>Bornean and Sumatran orangutans differ a little in appearance and behavior. While both have shaggy reddish fur, Sumatran orangutans have longer facial hair. Sumatran orangutans are reported to have closer social bonds than their Bornean cousins. Bornean orangutans are more likely to descend from the trees to move around on the ground. Both species have experienced sharp population declines. A century ago there were probably more than 230,000 orangutans in total, but the Bornean orangutan is now estimated at about 104,700 based on updated geographic range (Endangered) and the Sumatran about 7,500 (Critically Endangered).</p><p>A third species of orangutan was announced in November, 2017. With no more than 800 individuals in existence, the Tapanuli orangutan is the most endangered of all great apes.</p>",
        "timeToRead": 3,
        "image": "images/Animals_main/Orangutan.jpg",
        "sideImage": "images/Animals_main/African Savanna Elephant.jpg",
        "nextSideImage": "images/Animals_prev+next/Saola.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Javan Rhino.jpg",
        "status": "Critically Endangered",
        "height": "",
        "weight": "up to 200 pounds",
        "habitats": "",
        "scientiicName": "Pongo abelii, Pongo pygmaeus",
        "nextAnimalName": "Saola",
        "previousAnimalName": "Javan Rhino",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 13,
        "Name": "Saola",
        "animalIntroduction": "<p>The saola was discovered in May 1992 during a joint survey carried out by the Ministry of Forestry of Vietnam and WWF in north-central Vietnam. The team found a skull with unusual long, straight horns in a hunter's home and knew it was something extraordinary. The find proved to be the first large mammal new to science in more than 50 years and one of the most spectacular zoological discoveries of the 20th century.</p><p>Saola (pronounced: sow-la) are recognized by two parallel horns with sharp ends, which can reach 20 inches in length and are found on both males and females. Meaning “spindle horns” in Vietnamese, they are a cousin of cattle but resemble an antelope. Saola have striking white markings on the face and large maxillary glands on the muzzle, which could be used to mark territory or attract mates. They are found only in the Annamite Mountains of Vietnam and Laos.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Saola.jpg",
        "sideImage": "https://files.worldwildlife.org/wwfcmsprod/images/Saola/story_full_width/28r1fguqg7_Saola_Circle_image_HI_37218.jpg",
        "nextSideImage": "images/Animals_prev+next/Sumatran Elephant.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Orangutan.jpg",
        "status": "Critically Endangered",
        "height": "Average 33 inches at the shoulder",
        "weight": "176-220 lbs",
        "habitats": "Evergreen forests with little or no dry season",
        "scientiicName": "Pseudoryx nghetinhensis",
        "nextAnimalName": "Sumatran Elephant",
        "previousAnimalName": "Orangutan",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 14,
        "Name": "Sumatran Elephant",
        "animalIntroduction": "<p>Sumatran elephants feed on a variety of plants and deposit seeds wherever they go, contributing to a healthy forest ecosystem. They also share their lush forest habitat with several other endangered species, such as the Sumatran rhino, tiger, and orangutan, and countless other species that all benefit from an elephant population that thrives in a healthy habitat.</p>",
        "timeToRead": 1,
        "image": "images/Animals_main/Sumatran Elephant.jpg",
        "sideImage": "https://files.worldwildlife.org/wwfcmsprod/images/Sumatran_elephant_calf_08.10.2012_Species/story_full_width/1oltoese9m_MID_247516.jpg",
        "nextSideImage": "images/Animals_prev+next/Sumatran Orangutan.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Saola.jpg",
        "status": "Critically Endangered",
        "height": "5-9 feet at the shoulder",
        "weight": "approximately 5 tons",
        "habitats": "Broadleaf moist tropical forests",
        "scientiicName": "Elephas maximus sumatranus",
        "nextAnimalName": "Sumatran Orangutan",
        "previousAnimalName": "Saola",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 15,
        "Name": "Sumatran Orangutan",
        "animalIntroduction": "<p>The Sumatran orangutan is almost exclusively arboreal, living among the trees of tropical rainforests. Females virtually never travel on the ground and adult males do so rarely. Sumatran orangutans are reported to have closer social ties than their Bornean cousins. This has been attributed to mass fruit on fig trees, where groups of Sumatran orangutans can come together to feed. Adult males are typically solitary while females are accompanied by offspring.</p><p>Historically, the Sumatran orangutan was distributed over the entire island of Sumatra and further south into Java. The species' range is now restricted to the north of the island with a majority in the provinces of North Sumatra and Aceh. Of the nine existing populations of Sumatran orangutans, only seven have prospects of long-term viability, each with an estimated 250 or more individuals. Only three populations contain more than 1,000 orangutans. Orangutans that were confiscated from the illegal trade or as pets are being reintroduced to Bukit Tigapuluh National Park. They number around 70 and are reproducing. </p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Sumatran Orangutan.jpg",
        "sideImage": "https://neprimateconservancy.org/wp-content/uploads/2021/10/sumatran-orangutan-iStock-876642676-resize.jpg",
        "nextSideImage": "images/Animals_prev+next/Sumatran Rhino.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Sumatran Elephant.jpg",
        "status": "Critically Endangered",
        "height": "4 -5 feet",
        "weight": "66 – 198 pounds",
        "habitats": "Tropical and Subtropical Moist Broadleaf Forests",
        "scientiicName": "Pongo abelii",
        "nextAnimalName": "Sumatran Rhino",
        "previousAnimalName": "Sumatran Elephant",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 16,
        "Name": "Sumatran Rhino",
        "animalIntroduction": "<p>Sumatran rhinos are the smallest of the living rhinoceroses and the only Asian rhino with two horns. They are covered with long hair and are more closely related to the extinct woolly rhinos than any of the other rhino species alive today. Calves are born with a dense covering that turns reddish-brown in young adults and becomes sparse, bristly and almost black in older animals. Sumatran rhinos compete with the Javan rhino for the unenviable title of most threatened rhino species. While surviving in possibly greater numbers than the Javan rhino, Sumatran rhinos are more threatened due to habitat loss and fragmentation. The remaining animals survive in small, fragmented non-viable populations, and with limited possibilities to find each other to breed, its population decline continues. Just two captive females have reproduced in the last 15 years.</p><p>The Sumatran rhino once roamed as far away as the foothills of the Eastern Himalayas in Bhutan and eastern India, through Myanmar, Thailand, possibly to Vietnam and China, and south through the Malay Peninsula. Today, the species only survives on the Indonesian islands of Sumatra and Borneo. Experts believe the third subspecies is probably extinct.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Sumatran Rhino.jpg",
        "sideImage": "https://media.savetherhino.org/prod/uploads/2021/02/SumatranRhino_NickGarbuttPhotography.png",
        "nextSideImage": "images/Animals_prev+next/Sunda Tiger.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Sumatran Orangutan.jpg",
        "status": "Critically Endangered",
        "height": "3.3-5 feet",
        "weight": "1,320 -2,090 pounds",
        "habitats": "Dense highland and lowland tropical and sub-tropical forests",
        "scientiicName": "Dicerorhinus sumatrensis",
        "nextAnimalName": "Sunda Tiger",
        "previousAnimalName": "Sumatran Orangutan",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 17,
        "Name": "Sunda Tiger",
        "animalIntroduction": "<p>Sunda tigers are distinguished by heavy black stripes on their orange coats. The last of the Sunda island tigers—estimated to be fewer than 400 today—are holding on for survival in the remaining patches of forest on the island of Sumatra. Accelerating deforestation and rampant poaching mean this noble creature could end up extinct like its Javan and Balinese counterparts.</p><p>In Indonesia, anyone caught hunting tigers could face jail time and steep fines. But despite increased efforts in tiger conservation—including strengthening law enforcement and antipoaching capacity—a substantial market remains in Sumatra and other parts of Asia for tiger parts and products. Sunda tigers are losing their habitat and prey fast, and poaching is an ever-present threat.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Sunda Tiger.jpg",
        "sideImage": "https://files.worldwildlife.org/wwfcmsprod/images/Sumatran_Tiger/story_full_width/6b3ojsc0bk_sumatran_tiger_circle_44312149.jpg",
        "nextSideImage": "images/Animals_prev+next/Vaquita.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Sumatran Rhino.jpg",
        "status": "Critically Endangered",
        "height": "",
        "weight": "165–308 pounds",
        "habitats": "Tropical broadleaf evergreen forests, freshwater swamp forests and peat swamps",
        "scientiicName": "Panthera tigris sondaica",
        "nextAnimalName": "Vaquita",
        "previousAnimalName": "Sumatran Rhino",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 18,
        "Name": "Vaquita",
        "animalIntroduction": "<p>Vaquita, the world's rarest marine mammal, is on the edge of extinction. The plight of cetaceans—whales, dolphins, and porpoises—as a whole is exemplified by the rapid decline of the vaquita in Mexico, with about 10 individuals remaining. This little porpoise wasn't discovered until 1958 and a little over half a century later, we are on the brink of losing them forever. Vaquita are often caught and drowned in gillnets used by illegal fishing operations in marine protected areas within Mexico's Gulf of California. The population has dropped drastically in the last few years.</p><p>The vaquita has a large dark ring around its eyes and dark patches on its lips that form a thin line from the mouth to the pectoral fins. Its top—the dorsal surface—is dark gray, its sides are pale gray, and its underside—the ventral surface—is white with long, light gray markings. Newborn vaquita have darker coloration and a wide gray fringe of color that runs from the head to the flukes, passing through the dorsal and pectoral fins. They are most often found close to shore in the Gulf's shallow waters, although they quickly swim away if a boat approaches.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Vaquita.jpg",
        "sideImage": "https://www.mmc.gov/wp-content/uploads/21636854959_74086f9af8_o1.jpg",
        "nextSideImage": "images/Animals_prev+next/Western Lowland Gorilla.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Sunda Tiger.jpg",
        "status": "Critically Endangered",
        "height": "Up to 5 feet",
        "weight": "Up to 120 pounds",
        "habitats": "Marine (only in the northern Gulf of California)",
        "scientiicName": "Phocoena sinus",
        "nextAnimalName": "Western Lowland Gorilla",
        "previousAnimalName": "Sunda Tiger",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 19,
        "Name": "Western Lowland Gorilla",
        "animalIntroduction": "<p>The western lowland gorilla is the most numerous and widespread of all gorilla subspecies. Populations can be found in Cameroon, the Central African Republic, the Democratic Republic of Congo and Equatorial Guinea as well as in large areas in Gabon and the Republic of Congo. The exact number of western lowland gorillas is not known because they inhabit some of the most dense and remote rainforests in Africa. Significant populations still exist, including in isolated swamps and the remote swampy forests of the Republic of Congo.</p><p>Western lowland gorillas can be distinguished from other gorilla subspecies by their slightly smaller size, their brown-grey coats and auburn chests. They also have wider skulls with more pronounced brow ridges and smaller ears. Large numbers have not protected the western lowland gorilla from decline. Because of poaching and disease, the gorilla’s numbers have declined by more than 60% over the last 20 to 25 years. Even if all of the threats to western lowland gorillas were removed, scientists calculate that the population would require some 75 years to recover.</p>",
        "timeToRead": 2,
        "image": "images/Animals_main/Western Lowland Gorilla.jpg",
        "sideImage": "https://files.worldwildlife.org/wwfcmsprod/images/Western_Lowland_Gorilla/story_full_width/1gc8wt12cz_Gorilla_07.24.2012_Help.jpg",
        "nextSideImage": "images/Animals_prev+next/Yangtze Finless Porpoise.jpg",
        "PreviousSideImage": "images/Animals_prev+next/Vaquita.jpg",
        "status": "Critically Endangered",
        "height": "4 to 5 ½ feet when standing on two feet",
        "weight": "up to 440 pounds",
        "habitats": "",
        "scientiicName": "Gorilla gorilla gorilla",
        "nextAnimalName": "Yangtze Finless Porpoise",
        "previousAnimalName": "Vaquita",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    },
    {
        "id": 20,
        "Name": "Yangtze Finless Porpoise",
        "animalIntroduction": "<p>The Yangtze River, the longest river in Asia, used to be one of the only two rivers in the world that was home to two different species of dolphin—the Yangtze finless porpoise and the Baiji dolphin. However, in 2006 the Baiji dolphin was declared functionally extinct. This was the first time in history that an entire species of dolphin had been wiped off the planet because of human activity. Its close cousin, the Yangtze finless porpoise, is known for its mischievous smile and has a level of intelligence comparable to that of a gorilla.</p>",
        "timeToRead": 1,
        "image": "images/Animals_main/Yangtze Finless Porpoise.jpg",
        "sideImage": "",
        "nextSideImage": "images/Animals_prev+next/African Forest Elephant.jpeg",
        "PreviousSideImage": "images/Animals_prev+next/Western Lowland Gorilla.jpg",
        "status": "Critically Endangered",
        "height": "6.2 feet",
        "weight": "",
        "habitats": "Lakes & Rivers",
        "scientiicName": "Neophocaena asiaeorientalis ssp. asiaeorientalis",
        "nextAnimalName": "African Forest Elephant",
        "previousAnimalName": "Western Lowland Gorilla",
        "nextAnimalStatus": "Critically Endangered",
        "previousAnimalAtatus": "Critically Endangered"
    }
]